### ISSUE TITLE
Re-Cluster tab throws a network error in AWS version

### ISSUE THREAD

**Issue by AmyOlex** [VCUWrightCenter/TopExApp#90]
On AWS version the re-cluster tab throws a network error for Safari and Chrome browsers.

**Comment by etfrenchvcu** [comment]
@AmyOlex it appears that AWS Elastic Beanstalk is throttling the request because of size limits. I've seen some posts saying requests are limited to 5MB, but I know the initial cluster request works when >5MB, so maybe the 5MB doesn't count files? I'm not sure, and I've tried all the configuration updates that I could find and none of them worked. At this point, it does not seem that I'll be able to fix this problem on AWS and I've removed the recluster tab entirely on the site. I think for a more permanent hosting solution, it makes more sense to host TopEx on a VCU server anyway (with a vcu.edu domain), which ought to resolve the issue.

**Comment by AmyOlex** [comment]
I'm ok with that.  Thanks for investigating!


*Amy L. Olex*
Senior Bioinformatics Specialist
C. Kenneth and Dianne Wright Center for Clinical and Translational Research

Virginia Commonwealth University
203 E. Cary St, Suite 200
P.O. Box 980261
Richmond, VA 23298

Phone: 804-828-1621
Office: 213

*Please Remember!  If my consultation or services have contributed towards
a manuscript or other type of publication please cite the CTSA Grant*
*UL1TR002649
in the acknowledgements, which funds all services offered by the CCTR.*

**Comment by AmyOlex** [comment]
Looks like this has been fixed as I've re-tested it and no errors!
